/**
 * Prepare the WCS brand logo for the storefront.
 *
 * Reads one logo artwork file and writes web-ready brand assets:
 *   public/brand/monogram-{light,dark}.png   -> <BrandMark variant="monogram">  (navbar)
 *   public/brand/lockup-{light,dark}.png     -> <BrandMark variant="lockup">    (footer)
 *   public/brand/organization-logo.png       -> JSON-LD Organization logo
 *   public/brand/og.jpg                       -> OpenGraph / social share (1200x630)
 *   public/brand/dimensions.json              -> intrinsic sizes for <BrandMark>
 *   src/app/icon.png                          -> favicon (Next auto-discovery)
 *   src/app/apple-icon.png                    -> apple-touch-icon
 *
 * The source art (logo1.webp) is a raster with a BAKED cream background and no
 * transparency, so the cream is keyed out here (threshold + feather + fringe
 * spill suppression). If a transparent PNG/SVG is ever supplied instead, this
 * script detects the alpha channel and skips keying — nothing else changes.
 *
 * A dark-theme variant is generated by flattening every opaque pixel to a
 * single cream ink (#F1E8DD): the wine ink is near-invisible on the dark
 * theme ground (#100D0E).
 *
 * Manual / rare — NOT part of `npm run build`. Re-run when the artwork changes.
 *
 * Usage:
 *   node scripts/prepare-logo.mjs "C:/Users/you/Desktop/sample pics wcs/logo1.webp"
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import process from "node:process";
import sharp from "sharp";

const SRC = process.argv[2];
if (!SRC) {
  console.error(
    'Pass the logo file, e.g. node scripts/prepare-logo.mjs "C:/Users/you/Desktop/sample pics wcs/logo1.webp"',
  );
  process.exit(1);
}

const BRAND_OUT = path.join(process.cwd(), "public", "brand");
const APP_OUT = path.join(process.cwd(), "src", "app");

// ── Source-specific constants (measured from logo1.webp, 1536x1024) ──────────
const CREAM = { r: 0xfa, g: 0xf2, b: 0xe7 }; // baked background
const INK = { r: 0x50, g: 0x17, b: 0x24 }; // avg wine ink — fringe spill target
const DARK_INK = { r: 0xf1, g: 0xe8, b: 0xdd }; // cream ink for the dark theme

// Crop boxes into the source (left, top, width, height). The wordmark
// ("WEAVERS…") starts at ~x795 in the source, so the monogram crop must stop
// well before that or the favicon/navbar mark picks up stray letter fragments.
// The monogram is cropped tight to the "WcS" letters (the long saree tail is
// dropped — at navbar/favicon size it just reads as a stray mark); the footer
// lockup keeps the full drape.
const MONOGRAM = { left: 58, top: 296, width: 660, height: 428 };
const LOCKUP = { left: 55, top: 288, width: 1425, height: 548 };

// Cream-key thresholds: colour distance from CREAM.
const KEY_T1 = 16; //  <= this  -> fully transparent
const KEY_T2 = 46; //  >= this  -> fully opaque; linear alpha ramp between
const PAD_PCT = 0.035; // optical padding added after trim

// Target resize widths (resize inputs, not asserted results — see dimensions.json).
const MONOGRAM_W = 440;
const LOCKUP_W = 1080;

// ── Cream keying ────────────────────────────────────────────────────────────

/** Perceptual-ish weighted RGB distance. */
function dist(r, g, b, c) {
  const dr = r - c.r;
  const dg = g - c.g;
  const db = b - c.b;
  return Math.sqrt(2 * dr * dr + 4 * dg * dg + 3 * db * db) / 3;
}

/**
 * Extract `box` from the source and key the cream background to transparency.
 * Returns a sharp instance built from the raw RGBA buffer.
 */
async function keyCream(base, box) {
  const { data, info } = await base
    .clone()
    .extract(box)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const { width, height } = info;
  const px = width * height;
  for (let i = 0; i < px; i++) {
    const o = i * 4;
    const r = data[o];
    const g = data[o + 1];
    const b = data[o + 2];
    const d = dist(r, g, b, CREAM);

    let alpha;
    if (d <= KEY_T1) alpha = 0;
    else if (d >= KEY_T2) alpha = 255;
    else alpha = Math.round((255 * (d - KEY_T1)) / (KEY_T2 - KEY_T1));

    data[o + 3] = alpha;

    // Fringe spill suppression: pull partially-transparent (antialiased) pixels
    // toward the ink so they stop carrying cream and haloing.
    if (alpha > 0 && alpha < 255) {
      const t = alpha / 255; // 1 = solid ink, 0 = was cream
      data[o] = Math.round(r * t + INK.r * (1 - t));
      data[o + 1] = Math.round(g * t + INK.g * (1 - t));
      data[o + 2] = Math.round(b * t + INK.b * (1 - t));
    }
  }

  return sharp(data, { raw: { width, height, channels: 4 } });
}

const TRANSPARENT = { r: 0, g: 0, b: 0, alpha: 0 };

/**
 * Trim fully-transparent margins, then re-add even transparent padding.
 * Returns a PNG buffer. Each step is its own sharp pass so sharp's fixed
 * internal op order (resize before extend) can't reorder things unexpectedly.
 */
async function trimAndPad(img) {
  const trimmed = await img
    .clone()
    .trim({ threshold: 10 })
    .png()
    .toBuffer({ resolveWithObject: true })
    .catch(() =>
      // trim throws if it would remove the whole image — fall back untouched
      img.clone().png().toBuffer({ resolveWithObject: true }),
    );

  const padX = Math.round(trimmed.info.width * PAD_PCT);
  const padY = Math.round(trimmed.info.height * PAD_PCT);

  return sharp(trimmed.data)
    .extend({ top: padY, bottom: padY, left: padX, right: padX, background: TRANSPARENT })
    .png()
    .toBuffer();
}

/** trimAndPad → resize to `width` → sharpen → PNG buffer. */
async function finishMark(img, width) {
  const padded = await trimAndPad(img);
  return sharp(padded)
    .resize({ width, withoutEnlargement: true })
    .sharpen({ sigma: 0.6 })
    .png({ compressionLevel: 9 })
    .toBuffer();
}

/** Flatten every opaque-ish pixel to a single flat colour, keeping alpha. */
async function recolorFlat(pngBuffer, target) {
  const { data, info } = await sharp(pngBuffer)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  const px = info.width * info.height;
  for (let i = 0; i < px; i++) {
    const o = i * 4;
    if (data[o + 3] > 0) {
      data[o] = target.r;
      data[o + 1] = target.g;
      data[o + 2] = target.b;
    }
  }
  return sharp(data, {
    raw: { width: info.width, height: info.height, channels: 4 },
  })
    .png({ compressionLevel: 9 })
    .toBuffer();
}

/** Composite a transparent mark centred on a solid cream square. */
async function onCream(markPng, size, radius) {
  const inner = Math.round(size * 0.76); // ~12% margin each side
  const mark = await sharp(markPng)
    .resize(inner, inner, {
      fit: "contain",
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    })
    .toBuffer();

  let canvas = sharp({
    create: {
      width: size,
      height: size,
      channels: 4,
      background: { ...CREAM, alpha: 1 },
    },
  }).composite([{ input: mark, gravity: "centre" }]);

  if (radius > 0) {
    const mask = Buffer.from(
      `<svg width="${size}" height="${size}"><rect width="${size}" height="${size}" rx="${radius}" ry="${radius}" fill="#fff"/></svg>`,
    );
    canvas = sharp(await canvas.png().toBuffer()).composite([
      { input: mask, blend: "dest-in" },
    ]);
  }
  return canvas.png({ compressionLevel: 9 }).toBuffer();
}

async function pngDims(buffer) {
  const m = await sharp(buffer).metadata();
  return { w: m.width, h: m.height };
}

// ── Main ───────────────────────────────────────────────────────────────────

async function main() {
  if (!(await fs.stat(SRC).catch(() => null))) {
    console.error("Logo file not found:", SRC);
    process.exit(1);
  }

  await fs.mkdir(BRAND_OUT, { recursive: true });

  const base = sharp(SRC, { failOn: "none" }).rotate();
  const meta = await base.metadata();
  const hasAlpha = !!meta.hasAlpha;
  console.log(
    `Source: ${meta.width}x${meta.height} ${meta.format}` +
      (hasAlpha ? " (has alpha — skipping cream key)" : " (opaque — keying cream)"),
  );

  // A clean source with its own alpha bypasses keyCream entirely.
  const extract = (box) =>
    hasAlpha
      ? base.clone().extract(box).ensureAlpha()
      : keyCream(base, box);

  // ── monogram (navbar) ──
  const monoLight = await finishMark(await extract(MONOGRAM), MONOGRAM_W);
  const monoDark = await recolorFlat(monoLight, DARK_INK);
  await fs.writeFile(path.join(BRAND_OUT, "monogram-light.png"), monoLight);
  await fs.writeFile(path.join(BRAND_OUT, "monogram-dark.png"), monoDark);
  const monoDims = await pngDims(monoLight);

  // ── lockup (footer) ──
  const lockLight = await finishMark(await extract(LOCKUP), LOCKUP_W);
  const lockDark = await recolorFlat(lockLight, DARK_INK);
  await fs.writeFile(path.join(BRAND_OUT, "lockup-light.png"), lockLight);
  await fs.writeFile(path.join(BRAND_OUT, "lockup-dark.png"), lockDark);
  const lockDims = await pngDims(lockLight);

  // ── icons (from the monogram, on a cream ground) ──
  const monoMark = await trimAndPad(await extract(MONOGRAM));
  const icon512 = await onCream(monoMark, 512, 82);

  // Favicon + apple-touch-icon: Next auto-discovers these from src/app/.
  await fs.writeFile(path.join(APP_OUT, "icon.png"), icon512);
  await fs.writeFile(
    path.join(APP_OUT, "apple-icon.png"),
    await sharp(await onCream(monoMark, 180, 0))
      .flatten({ background: CREAM })
      .png({ compressionLevel: 9 })
      .toBuffer(),
  );

  // Square icons served from /brand/ — used by manifest.ts and JSON-LD.
  await fs.writeFile(path.join(BRAND_OUT, "icon-512.png"), icon512);
  await fs.writeFile(
    path.join(BRAND_OUT, "icon-192.png"),
    await onCream(monoMark, 192, 30),
  );

  // ── OG image (lockup centred on cream, 1200x630) ──
  const lockMark = await sharp(await trimAndPad(await extract(LOCKUP)))
    .resize({ width: 980, withoutEnlargement: true })
    .png()
    .toBuffer();
  const og = sharp({
    create: {
      width: 1200,
      height: 630,
      channels: 4,
      background: { ...CREAM, alpha: 1 },
    },
  }).composite([{ input: lockMark, gravity: "centre" }]);
  await fs.writeFile(
    path.join(BRAND_OUT, "og.jpg"),
    await og.flatten({ background: CREAM }).jpeg({ quality: 82, mozjpeg: true }).toBuffer(),
  );

  // ── dimensions.json (intrinsic sizes for <BrandMark>) ──
  const dimensions = { monogram: monoDims, lockup: lockDims };
  await fs.writeFile(
    path.join(BRAND_OUT, "dimensions.json"),
    JSON.stringify(dimensions, null, 2) + "\n",
  );

  console.log("\nWrote:");
  console.log(`  public/brand/monogram-light.png  ${monoDims.w}x${monoDims.h}`);
  console.log(`  public/brand/monogram-dark.png   ${monoDims.w}x${monoDims.h}`);
  console.log(`  public/brand/lockup-light.png    ${lockDims.w}x${lockDims.h}`);
  console.log(`  public/brand/lockup-dark.png     ${lockDims.w}x${lockDims.h}`);
  console.log("  public/brand/icon-512.png           512x512");
  console.log("  public/brand/icon-192.png           192x192");
  console.log("  public/brand/og.jpg                 1200x630");
  console.log("  public/brand/dimensions.json");
  console.log("  src/app/icon.png                    512x512");
  console.log("  src/app/apple-icon.png              180x180");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
